services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    volumes:
      - ./src:/app/project/src
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    networks:
      - restaurant-net


networks:
  restaurant-net:
    external: true