services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    volumes:
      - ./src:/app/project/src
    ports:
      - "3002:3000"
    env_file:
      - .env
    networks:
      - restaurant-net


networks:
  restaurant-net:
    external: true